const recessOrder = require('stylelint-config-recess-order');

module.exports = {
	reportDescriptionlessDisables: true,
	reportInvalidScopeDisables:    true,
	reportNeedlessDisables:        true,
	plugins:                       [require.resolve('stylelint-declaration-block-no-ignored-properties'), require.resolve('stylelint-order'), require.resolve('stylelint-scss')],
	rules:                         {
		'alpha-value-notation':                  'percentage',
		'at-rule-allowed-list':                  null,
		'at-rule-disallowed-list':               null,
		'at-rule-empty-line-before':             ['always', { except: ['blockless-after-same-name-blockless', 'first-nested'] }],
		'at-rule-name-case':                     'lower',
		'at-rule-name-newline-after':            'always-multi-line',
		'at-rule-name-space-after':              'always-single-line',
		'at-rule-no-unknown':                    null,
		'at-rule-no-vendor-prefix':              true,
		'at-rule-property-required-list':        null,
		'at-rule-semicolon-newline-after':       'always',
		'at-rule-semicolon-space-before':        'never',
		'block-closing-brace-empty-line-before': 'never',
		'block-closing-brace-newline-after':     'always',
		'block-closing-brace-newline-before':    'always',
		'block-closing-brace-space-after':       'always-single-line',
		'block-closing-brace-space-before':      'always-single-line',
		'block-no-empty':                        [true, { ignore: 'comments' }],
		'block-opening-brace-newline-after':     'always',
		'block-opening-brace-newline-before':    null,
		'block-opening-brace-space-after':       'always-single-line',
		'block-opening-brace-space-before':      'always',
		'color-function-notation':               'legacy',
		'color-hex-case':                        'lower',
		'color-hex-length':                      'long',
		'color-named':                           ['never', { ignoreProperties: 'composes' }],
		'color-no-hex':                          null,
		'color-no-invalid-hex':                  true,
		'comment-empty-line-before':             [
			'always',
			{
				except: 'first-nested',
				ignore: 'stylelint-commands',
			},
		],
		'comment-no-empty':                                   true,
		'comment-pattern':                                    null,
		'comment-whitespace-inside':                          'always',
		'comment-word-disallowed-list':                       null,
		'custom-media-pattern':                               null,
		'custom-property-empty-line-before':                  'never',
		'custom-property-pattern':                            null,
		'declaration-bang-space-after':                       'never',
		'declaration-bang-space-before':                      'always',
		'declaration-block-no-duplicate-custom-properties':   true,
		'declaration-block-no-duplicate-properties':          [true, { ignoreProperties: ['composes'] }],
		'declaration-block-no-redundant-longhand-properties': null,
		'declaration-block-no-shorthand-property-overrides':  true,
		'declaration-block-semicolon-newline-after':          'always',
		'declaration-block-semicolon-newline-before':         'never-multi-line',
		'declaration-block-semicolon-space-after':            'always-single-line',
		'declaration-block-semicolon-space-before':           'never',
		'declaration-block-single-line-max-declarations':     0,
		'declaration-block-trailing-semicolon':               'always',
		'declaration-colon-newline-after':                    'always-multi-line',
		'declaration-colon-space-after':                      'always-single-line',
		'declaration-colon-space-before':                     'never',
		'declaration-empty-line-before':                      'never',
		'declaration-no-important':                           true,
		'declaration-property-unit-allowed-list':             [{ 'font-size': ['rem'] }, { severity: 'warning' }],
		'declaration-property-unit-disallowed-list':          null,
		'declaration-property-value-allowed-list':            null,
		'declaration-property-value-disallowed-list':         null,
		'font-family-name-quotes':                            'always-unless-keyword',
		'font-family-no-duplicate-names':                     true,
		'font-family-no-missing-generic-family-keyword':      [true, { severity: 'warning' }],
		'font-weight-notation':                               null,
		'function-allowed-list':                              null,
		'function-calc-no-invalid':                           true,
		'function-calc-no-unspaced-operator':                 true,
		'function-comma-newline-after':                       'always-multi-line',
		'function-comma-newline-before':                      'never-multi-line',
		'function-comma-space-after':                         'always-single-line',
		'function-comma-space-before':                        'never',
		'function-disallowed-list':                           null,
		'function-linear-gradient-no-nonstandard-direction':  true,
		'function-max-empty-lines':                           0,
		'function-name-case':                                 'lower',
		'function-parentheses-newline-inside':                'always-multi-line',
		'function-parentheses-space-inside':                  'never-single-line',
		'function-url-no-scheme-relative':                    true,
		'function-url-quotes':                                ['always', { except: 'empty' }],
		'function-url-scheme-allowed-list':                   ['data', '/^http/'],
		'function-url-scheme-disallowed-list':                null,
		'function-whitespace-after':                          'always',
		'hue-degree-notation':                                'angle',
		'indentation':                                        'tab',
		'keyframe-declaration-no-important':                  true,
		'keyframes-name-pattern':                             null,
		'length-zero-no-unit':                                true,
		'linebreaks':                                         'unix',
		'max-empty-lines':                                    1,
		'max-line-length':                                    null,
		'max-nesting-depth':                                  null,
		'media-feature-colon-space-after':                    'always',
		'media-feature-colon-space-before':                   'never',
		'media-feature-name-allowed-list':                    null,
		'media-feature-name-case':                            'lower',
		'media-feature-name-disallowed-list':                 [
			'^max-width',
			{
				message:  'Use min-width for a mobile-first approach (media-feature-name-disallowed-list)',
				severity: 'warning',
			},
		],
		'media-feature-name-no-unknown':             true,
		'media-feature-name-no-vendor-prefix':       true,
		'media-feature-name-value-allowed-list':     null,
		'media-feature-parentheses-space-inside':    'never',
		'media-feature-range-operator-space-after':  'always',
		'media-feature-range-operator-space-before': 'always',
		'media-query-list-comma-newline-after':      'always',
		'media-query-list-comma-newline-before':     'never-multi-line',
		'media-query-list-comma-space-after':        'always-single-line',
		'media-query-list-comma-space-before':       'never',
		'named-grid-areas-no-invalid':               true,
		'no-descending-specificity':                 true,
		'no-duplicate-at-import-rules':              true,
		'no-duplicate-selectors':                    true,
		'no-empty-first-line':                       true,
		'no-empty-source':                           [true, { severity: 'warning' }],
		'no-eol-whitespace':                         true,
		'no-extra-semicolons':                       true,
		'no-invalid-double-slash-comments':          null, // Should be enabled for scss https://github.com/stylelint/stylelint/issues/3128
		'no-missing-end-of-source-newline':          true,
		'no-unknown-animations':                     null,
		'number-leading-zero':                       'always',
		'number-max-precision':                      null,
		'number-no-trailing-zeros':                  true,
		'order/order':                               [
			[
				'less-mixins',
				'custom-properties',
				'dollar-variables',
				'at-variables',
				{
					type:     'at-rule',
					hasBlock: false,
				},
				'declarations',
			],
			{ unspecified: 'bottom' },
		],
		'order/properties-alphabetical-order': null,
		'order/properties-order':              [
			[
				// For Styled-Components
				{
					order:      'flexible',
					properties: [
						'-styled-mixin0',
						'-styled-mixin1',
						'-styled-mixin2',
						'-styled-mixin3',
						'-styled-mixin4',
						'-styled-mixin5',
						'-styled-mixin6',
						'-styled-mixin7',
						'-styled-mixin8',
						'-styled-mixin9',
					],
				},
				{ properties: ['composes'] },
				...recessOrder.rules['order/properties-order'],
			],
			{ unspecified: 'bottomAlphabetical' },
		],
		'plugin/declaration-block-no-ignored-properties':       true,
		'property-allowed-list':                                null,
		'property-case':                                        'lower',
		'property-disallowed-list':                             null,
		'property-no-unknown':                                  [true, { ignoreProperties: ['composes'] }],
		'property-no-vendor-prefix':                            true,
		'rule-empty-line-before':                               ['always', { except: ['first-nested'] }],
		'scss/at-each-key-value-single-line':                   true,
		'scss/at-else-closing-brace-newline-after':             'always-last-in-chain',
		'scss/at-else-closing-brace-space-after':               'always-intermediate',
		'scss/at-else-empty-line-before':                       'never',
		'scss/at-else-if-parentheses-space-before':             'always',
		'scss/at-extend-no-missing-placeholder':                null,
		'scss/at-function-named-arguments':                     null,
		'scss/at-function-parentheses-space-before':            'never',
		'scss/at-function-pattern':                             null,
		'scss/at-import-partial-extension':                     'always',
		'scss/at-if-closing-brace-newline-after':               'always-last-in-chain',
		'scss/at-if-closing-brace-space-after':                 'always-intermediate',
		'scss/at-if-no-null':                                   true,
		'scss/at-import-no-partial-leading-underscore':         null,
		'scss/at-import-partial-extension-blacklist':           null,
		'scss/at-import-partial-extension-whitelist':           null,
		'scss/at-mixin-argumentless-call-parentheses':          'never',
		'scss/at-mixin-named-arguments':                        null,
		'scss/at-mixin-parentheses-space-before':               'never',
		'scss/at-mixin-pattern':                                null,
		'scss/at-rule-conditional-no-parentheses':              null,
		'scss/at-rule-no-unknown':                              [true, { ignoreAtRules: ['import'] }],
		'scss/comment-no-empty':                                true,
		'scss/comment-no-loud':                                 null,
		'scss/declaration-nested-properties':                   'never',
		'scss/declaration-nested-properties-no-divided-groups': true,
		'scss/dimension-no-non-numeric-values':                 null,
		'scss/dollar-variable-colon-newline-after':             'always-multi-line',
		'scss/dollar-variable-colon-space-after':               'always-single-line',
		'scss/dollar-variable-colon-space-before':              'never',
		'scss/dollar-variable-default':                         null,
		'scss/dollar-variable-empty-line-after':                null,
		'scss/dollar-variable-empty-line-before':               ['always', { except: ['first-nested', 'after-comment', 'after-dollar-variable'] }],
		'scss/dollar-variable-first-in-block':                  null,
		'scss/dollar-variable-no-missing-interpolation':        true,
		'scss/dollar-variable-pattern':                         null,
		'scss/double-slash-comment-empty-line-before':          'never',
		'scss/double-slash-comment-inline':                     null,
		'scss/double-slash-comment-whitespace-inside':          'always',
		'scss/function-color-relative':                         null,
		'scss/function-quote-no-quoted-strings-inside':         null,
		'scss/function-unquote-no-unquoted-strings-inside':     true,
		'scss/map-keys-quotes':                                 null,
		'scss/media-feature-value-dollar-variable':             null,
		'scss/no-dollar-variables':                             null,
		'scss/no-duplicate-dollar-variables':                   true,
		'scss/no-duplicate-mixins':                             true,
		'scss/no-global-function-names':                        true,
		'scss/operator-no-newline-after':                       null,
		'scss/operator-no-newline-before':                      true,
		'scss/operator-no-unspaced':                            true,
		'scss/partial-no-import':                               null,
		'scss/percent-placeholder-pattern':                     null,
		'scss/selector-nest-combinators':                       'always',
		'scss/selector-no-redundant-nesting-selector':          true,
		'scss/selector-no-union-class-name':                    null,
		'selector-attribute-brackets-space-inside':             'never',
		'selector-attribute-name-disallowed-list':              null,
		'selector-attribute-operator-allowed-list':             null,
		'selector-attribute-operator-disallowed-list':          null,
		'selector-attribute-operator-space-after':              'never',
		'selector-attribute-operator-space-before':             'never',
		'selector-attribute-quotes':                            'always',
		'selector-class-pattern':                               null,
		'selector-combinator-allowed-list':                     null,
		'selector-combinator-disallowed-list':                  null,
		'selector-combinator-space-after':                      'always',
		'selector-combinator-space-before':                     'always',
		'selector-descendant-combinator-no-non-space':          true,
		'selector-id-pattern':                                  null,
		'selector-list-comma-newline-after':                    'always',
		'selector-list-comma-newline-before':                   'never-multi-line',
		'selector-list-comma-space-after':                      'always-single-line',
		'selector-list-comma-space-before':                     'never',
		'selector-max-attribute':                               null,
		'selector-max-class':                                   null,
		'selector-max-combinators':                             null,
		'selector-max-compound-selectors':                      null,
		'selector-max-empty-lines':                             0,
		'selector-max-id':                                      0,
		'selector-max-pseudo-class':                            null,
		'selector-max-specificity':                             null,
		'selector-max-type':                                    [0, { message: 'Don\'t style html elements. It leads to css specificity issues.' }],
		'selector-max-universal':                               0,
		'selector-nested-pattern':                              null,
		'selector-no-qualifying-type':                          null,
		'selector-no-vendor-prefix':                            true,
		'selector-pseudo-class-allowed-list':                   null,
		'selector-pseudo-class-case':                           'lower',
		'selector-pseudo-class-disallowed-list':                null,
		'selector-pseudo-class-no-unknown':                     [true, { ignorePseudoClasses: ['global'] }],
		'selector-pseudo-class-parentheses-space-inside':       'never',
		'selector-pseudo-element-allowed-list':                 null,
		'selector-pseudo-element-case':                         'lower',
		'selector-pseudo-element-colon-notation':               'double',
		'selector-pseudo-element-disallowed-list':              null,
		'selector-pseudo-element-no-unknown':                   true,
		'selector-type-case':                                   'lower',
		'selector-type-no-unknown':                             true,
		'shorthand-property-no-redundant-values':               null,
		'string-no-newline':                                    true,
		'string-quotes':                                        ['single', { avoidEscape: false }],
		'time-min-milliseconds':                                null,
		'unicode-bom':                                          'never',
		'unit-allowed-list':                                    null,
		'unit-case':                                            'lower',
		'unit-disallowed-list':                                 null,
		'unit-no-unknown':                                      true,
		'value-keyword-case':                                   [
			'lower',
			{
				ignoreKeywords:   ['dummyValue'],
				ignoreProperties: ['composes'],
			},
		],
		'value-list-comma-newline-after':  'always-multi-line',
		'value-list-comma-newline-before': 'never-multi-line',
		'value-list-comma-space-after':    'always-single-line',
		'value-list-comma-space-before':   'never',
		'value-list-max-empty-lines':      0,
		'value-no-vendor-prefix':          true,
	},
};
